### ISSUE TITLE
can't grant storage permission and upload photos on the Android 1.0.2337 version

### ISSUE THREAD

**Issue by brickli3755** [TopperDEL/StorjPhotoGalleryUploader#5]
Can you fix it ?

**Comment by TopperDEL** [comment]
May you try the latest version? And do you have more information? What happens exactly?

**Comment by TopperDEL** [comment]
Ah, sorry. That is the latest version. But can you give more info what you try do do and what happens exactly?

**Comment by brickli3755** [comment]
Hi,Here is the situation.
https://cdn.ucany.net/2022/02/20/VPJtZefJ.gif

**Comment by brickli3755** [comment]
> Hi,Here is the situation. https://cdn.ucany.net/2022/02/20/VPJtZefJ.gif

its Android 11

**Comment by TopperDEL** [comment]
I found the error! I made a mistake with a control and placed them in the wrong order. So basically you could simply not click the button.
As I've concentrated on different aspects with that adjustment, I did not realize that error. Thanks for reporting! The build pipeline is running already and the update should be live the store in some hours.

Thanks for that issue!

**Comment by TopperDEL** [comment]
Update is live now
